version: "3.8"
services:
  datatitan_site:
    build: ./
    ports:
      - "8080:8000"
    networks:
      - frontend
      - backend
    secrets:
      - postgres_password
    depends_on:
      - db

  memcached:
    image: memcached:latest
    ports:
      - "11211"
    networks:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: DataTitans
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
    volumes:
    - db-data:/var/lib/postgresql/data
    networks:
      - backend
    ports:
    - "5432"


volumes:
  db-data:

secrets:
  postgres_password:
    file: cred/postgres_password.txt

networks:
  frontend:
    driver: bridge

  backend:
    driver: bridge