version: "3.8"
services:
  datatitan_site:
    build: ./
    ports:
      - "8080:8000"
    networks:
      - frontend
      - backend

  memcached:
    image: memcached:latest
    ports:
      - "11211"
    networks:
      - backend

  db:
    image: library/mysql:latest
    restart: always


volumes:
  db-data:

secrets:
  postgres_password:
    external: true

networks:
  frontend:
    driver:

  backend:
    driver: